[workspace]

members = [
    "oo-bindgen",

    "generators/c-oo-bindgen",
    "generators/dotnet-oo-bindgen",

    "example/dnp3",
    "example/dnp3-ffi",
    "example/dnp3-bindings",

    #"example/foo",
    #"example/foo-ffi",
]
