[package]
name = "dotnet-oo-bindgen"
version = "0.5.1"
authors = ["Step Function I/O LLC <info@stepfunc.io>"]
edition = "2021"

[dependencies]
oo-bindgen = { path = "../../oo-bindgen" }
dunce = "1.0"
tracing = "^0.1"
clap = { version = "^4", features = ["derive"] }

